[2023-02-14T15:03:29.152+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: simple.test_airflow scheduled__2023-02-13T00:00:00+00:00 [queued]>
[2023-02-14T15:03:29.181+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: simple.test_airflow scheduled__2023-02-13T00:00:00+00:00 [queued]>
[2023-02-14T15:03:29.183+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T15:03:29.186+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2023-02-14T15:03:29.188+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T15:03:29.242+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): test_airflow> on 2023-02-13 00:00:00+00:00
[2023-02-14T15:03:29.255+0000] {standard_task_runner.py:55} INFO - Started process 329 to run task
[2023-02-14T15:03:29.265+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'simple', 'test_***', 'scheduled__2023-02-13T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dag_qatoffside.py', '--cfg-path', '/tmp/tmpozqhpggh']
[2023-02-14T15:03:29.268+0000] {standard_task_runner.py:83} INFO - Job 23: Subtask test_***
[2023-02-14T15:03:29.399+0000] {task_command.py:389} INFO - Running <TaskInstance: simple.test_airflow scheduled__2023-02-13T00:00:00+00:00 [running]> on host 55b685598511
[2023-02-14T15:03:29.528+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=simple
AIRFLOW_CTX_TASK_ID=test_***
AIRFLOW_CTX_EXECUTION_DATE=2023-02-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-13T00:00:00+00:00
[2023-02-14T15:03:29.533+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-14T15:03:29.535+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /Users/radu.guran/Projects/FifaWorldCup22/scraper_specific.py']
[2023-02-14T15:03:29.556+0000] {subprocess.py:86} INFO - Output:
[2023-02-14T15:03:29.704+0000] {subprocess.py:93} INFO - python: can't open file '/Users/radu.guran/Projects/FifaWorldCup22/scraper_specific.py': [Errno 2] No such file or directory
[2023-02-14T15:03:29.710+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-02-14T15:03:29.731+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-14T15:03:29.759+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=simple, task_id=test_***, execution_date=20230213T000000, start_date=20230214T150329, end_date=20230214T150329
[2023-02-14T15:03:29.780+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 23 for task test_*** (Bash command failed. The command returned a non-zero exit code 2.; 329)
[2023-02-14T15:03:29.800+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-14T15:03:29.831+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
