[2023-02-15T15:55:57.724+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: abc.test_airflow manual__2023-02-15T15:50:51.911279+00:00 [queued]>
[2023-02-15T15:55:57.738+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: abc.test_airflow manual__2023-02-15T15:50:51.911279+00:00 [queued]>
[2023-02-15T15:55:57.739+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T15:55:57.741+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-02-15T15:55:57.742+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T15:55:57.764+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): test_airflow> on 2023-02-15 15:50:51.911279+00:00
[2023-02-15T15:55:57.772+0000] {standard_task_runner.py:55} INFO - Started process 42968 to run task
[2023-02-15T15:55:57.778+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'abc', 'test_***', 'manual__2023-02-15T15:50:51.911279+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/dag_qatoffside.py', '--cfg-path', '/tmp/tmp89q9a796']
[2023-02-15T15:55:57.780+0000] {standard_task_runner.py:83} INFO - Job 67: Subtask test_***
[2023-02-15T15:55:57.880+0000] {task_command.py:389} INFO - Running <TaskInstance: abc.test_airflow manual__2023-02-15T15:50:51.911279+00:00 [running]> on host 55b685598511
[2023-02-15T15:55:57.965+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=abc
AIRFLOW_CTX_TASK_ID=test_***
AIRFLOW_CTX_EXECUTION_DATE=2023-02-15T15:50:51.911279+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-15T15:50:51.911279+00:00
[2023-02-15T15:55:57.969+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-15T15:55:57.971+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/dags/scraper_specific.py']
[2023-02-15T15:55:57.986+0000] {subprocess.py:86} INFO - Output:
[2023-02-15T15:55:59.018+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-02-15T15:55:59.020+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scraper_specific.py", line 4, in <module>
[2023-02-15T15:55:59.021+0000] {subprocess.py:93} INFO -     from snowflake.sqlalchemy import URL
[2023-02-15T15:55:59.022+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'snowflake'
[2023-02-15T15:55:59.145+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-02-15T15:55:59.181+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-02-15T15:55:59.191+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=abc, task_id=test_***, execution_date=20230215T155051, start_date=20230215T155557, end_date=20230215T155559
[2023-02-15T15:55:59.220+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 67 for task test_*** (Bash command failed. The command returned a non-zero exit code 1.; 42968)
[2023-02-15T15:55:59.240+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-15T15:55:59.270+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
