[2023-02-14T15:08:32.302+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: simple.test_airflow scheduled__2023-02-12T00:00:00+00:00 [queued]>
[2023-02-14T15:08:32.384+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: simple.test_airflow scheduled__2023-02-12T00:00:00+00:00 [queued]>
[2023-02-14T15:08:32.386+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T15:08:32.390+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-02-14T15:08:32.396+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-14T15:08:32.447+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): test_airflow> on 2023-02-12 00:00:00+00:00
[2023-02-14T15:08:32.464+0000] {standard_task_runner.py:55} INFO - Started process 732 to run task
[2023-02-14T15:08:32.480+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'simple', 'test_***', 'scheduled__2023-02-12T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dag_qatoffside.py', '--cfg-path', '/tmp/tmp6v8n9c5w']
[2023-02-14T15:08:32.483+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask test_***
[2023-02-14T15:08:32.720+0000] {task_command.py:389} INFO - Running <TaskInstance: simple.test_airflow scheduled__2023-02-12T00:00:00+00:00 [running]> on host 55b685598511
[2023-02-14T15:08:33.067+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=simple
AIRFLOW_CTX_TASK_ID=test_***
AIRFLOW_CTX_EXECUTION_DATE=2023-02-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-12T00:00:00+00:00
[2023-02-14T15:08:33.078+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-14T15:08:33.081+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /Users/radu.guran/Projects/FifaWorldCup22/scraper_specific.py']
[2023-02-14T15:08:33.113+0000] {subprocess.py:86} INFO - Output:
[2023-02-14T15:08:33.365+0000] {subprocess.py:93} INFO - python: can't open file '/Users/radu.guran/Projects/FifaWorldCup22/scraper_specific.py': [Errno 2] No such file or directory
[2023-02-14T15:08:33.372+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-02-14T15:08:33.402+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-02-14T15:08:33.410+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=simple, task_id=test_***, execution_date=20230212T000000, start_date=20230214T150832, end_date=20230214T150833
[2023-02-14T15:08:33.435+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 29 for task test_*** (Bash command failed. The command returned a non-zero exit code 2.; 732)
[2023-02-14T15:08:33.459+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-14T15:08:33.494+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
