[2023-02-15T16:01:07.781+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: abc.test_airflow manual__2023-02-15T15:56:03.567506+00:00 [queued]>
[2023-02-15T16:01:07.791+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: abc.test_airflow manual__2023-02-15T15:56:03.567506+00:00 [queued]>
[2023-02-15T16:01:07.792+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T16:01:07.793+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2023-02-15T16:01:07.794+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-15T16:01:07.808+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): test_airflow> on 2023-02-15 15:56:03.567506+00:00
[2023-02-15T16:01:07.814+0000] {standard_task_runner.py:55} INFO - Started process 43410 to run task
[2023-02-15T16:01:07.819+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'abc', 'test_***', 'manual__2023-02-15T15:56:03.567506+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/dag_qatoffside.py', '--cfg-path', '/tmp/tmpchf40wbl']
[2023-02-15T16:01:07.821+0000] {standard_task_runner.py:83} INFO - Job 69: Subtask test_***
[2023-02-15T16:01:07.891+0000] {task_command.py:389} INFO - Running <TaskInstance: abc.test_airflow manual__2023-02-15T15:56:03.567506+00:00 [running]> on host 55b685598511
[2023-02-15T16:01:07.963+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@***.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=abc
AIRFLOW_CTX_TASK_ID=test_***
AIRFLOW_CTX_EXECUTION_DATE=2023-02-15T15:56:03.567506+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-15T15:56:03.567506+00:00
[2023-02-15T16:01:07.966+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-15T16:01:07.967+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/dags/scraper_specific.py']
[2023-02-15T16:01:07.981+0000] {subprocess.py:86} INFO - Output:
[2023-02-15T16:01:08.822+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-02-15T16:01:08.823+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scraper_specific.py", line 4, in <module>
[2023-02-15T16:01:08.824+0000] {subprocess.py:93} INFO -     from snowflake.sqlalchemy import URL
[2023-02-15T16:01:08.825+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'snowflake'
[2023-02-15T16:01:08.889+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-02-15T16:01:08.903+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-02-15T16:01:08.909+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=abc, task_id=test_***, execution_date=20230215T155603, start_date=20230215T160107, end_date=20230215T160108
[2023-02-15T16:01:08.926+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 69 for task test_*** (Bash command failed. The command returned a non-zero exit code 1.; 43410)
[2023-02-15T16:01:08.956+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-15T16:01:08.976+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
